### ISSUE TITLE
Há elementos faltantes no projeto

### ISSUE THREAD

**Issue by santos-fernando** [lucasfusinato/faasachat-project#1]
O projeto não contem a alocação de tarefas. O projeto também não informa quais são os integrantes da equipe. Favor providenciar isto com urgência para eu finalizar a avaliação e atribuir a nota. Favor responder esta issue assim que o push for feito.

**Comment by JoaoVictorArruda** [comment]
Foi adicionado no README.md os integrantes da equipe e suas respectivas tarefas.

**Comment by santos-fernando** [comment]
Ok, recebido. Realizei a avaliação e vou postar os comentários em uma nova issue.
